Repository OffchainLabs/arbitrum, pull requests merged in 2022-07, with the labels that each got.

#2331 Improve logging on reorg
  packages/arb-avm-cpp/data_storage/src/arbcore.cpp
  packages/arb-rpc-node/cmd/arb-node/arb-node.go
Labels: cla-signed

#2332 Improve logging on reorg
  packages/arb-avm-cpp/data_storage/src/arbcore.cpp
  packages/arb-rpc-node/cmd/arb-node/arb-node.go
Labels: cla-signed

#2312 anytrust chains w/ data availability committee docs page
  docs/AnyTrust.md
Labels: cla-signed

#2336 Update contract interfaces
  .circleci/config.yml
  packages/arb-bridge-eth/contracts/arch/IOneStepProof.sol
  packages/arb-bridge-eth/contracts/bridge/Inbox.sol
  packages/arb-bridge-eth/contracts/bridge/interfaces/IBridge.sol
  packages/arb-bridge-eth/contracts/bridge/interfaces/IInbox.sol
  packages/arb-bridge-eth/contracts/bridge/interfaces/IMessageProvider.sol
  packages/arb-bridge-eth/contracts/bridge/interfaces/IOutbox.sol
  packages/arb-bridge-eth/contracts/bridge/interfaces/ISequencerInbox.sol
  packages/arb-bridge-eth/contracts/challenge/IChallenge.sol
  packages/arb-bridge-eth/contracts/challenge/IChallengeFactory.sol
  packages/arb-bridge-eth/contracts/interfaces/IERC20.sol
  packages/arb-bridge-eth/contracts/interfaces/IERC721.sol
  packages/arb-bridge-eth/contracts/libraries/ICloneable.sol
  packages/arb-bridge-eth/contracts/rollup/INode.sol
  packages/arb-bridge-eth/contracts/rollup/INodeFactory.sol
  packages/arb-bridge-eth/contracts/rollup/IRollupCore.sol
  packages/arb-bridge-eth/contracts/rollup/facets/IRollupFacets.sol
  packages/arb-bridge-eth/contracts/validator/IGasRefunder.sol
  packages/arb-bridge-eth/hardhat.base-config.json
  packages/arb-bridge-eth/package.json
  packages/arb-bridge-peripherals/contracts/tokenbridge/arbitrum/IArbToken.sol
  packages/arb-bridge-peripherals/contracts/tokenbridge/ethereum/ICustomToken.sol
  packages/arb-bridge-peripherals/contracts/tokenbridge/libraries/ITransferAndCall.sol
  packages/arb-bridge-peripherals/contracts/tokenbridge/libraries/IWETH9.sol
  packages/arb-bridge-peripherals/contracts/tokenbridge/libraries/gateway/ICustomGateway.sol
  packages/arb-bridge-peripherals/contracts/tokenbridge/libraries/gateway/ITokenGateway.sol
  packages/arb-bridge-peripherals/contracts/tokenbridge/test/InterfaceCompatibilityTester.sol
  packages/arb-bridge-peripherals/hardhat.config.ts
  packages/arb-bridge-peripherals/package.json
Labels: arb-bridge-eth, arb-bridge-peripherals, cla-signed

#2330 Update Inbox contract deployment info
  packages/arb-bridge-eth/_deployments/1_current_deployment.json
  packages/arb-bridge-eth/_deployments/4_current_deployment.json
Labels: cla-signed

#2346 Don't reconnect to L1 because a receipt wasn't found
  packages/arb-util/ethutils/client.go
Labels: cla-signed

#2348 Add setOwner to L1CustomGateway
  packages/arb-bridge-peripherals/contracts/tokenbridge/ethereum/gateway/L1CustomGateway.sol
Labels: arb-bridge-peripherals, cla-signed

#2355 Update Public_Nitro_Devnet.md
  docs/Public_Nitro_Devnet.md
Labels: cla-signed

#2356 revert: L1 custom gateway lazy mint (PR #1713)
  packages/arb-bridge-peripherals/contracts/tokenbridge/ethereum/gateway/L1CustomGateway.sol
  packages/arb-bridge-peripherals/test/customGateway.e2e.ts
Labels: arb-bridge-peripherals, cla-signed

#2357 change 'devnet' to 'testnet' in docs
  docs/Public_Nitro_Devnet.md
Labels: cla-signed

#2358 one more rename
  docs/Public_Nitro_Testnet.md
Labels: cla-signed

#2341 fix typo in anytrust docs
  docs/AnyTrust.md
Labels: documentation, cla-signed

#2366 Allowlist npm advisory 1081522
  package.json
Labels: cla-signed

#2367 move goerli testnet rollup addresses to useful addresses page
  docs/Public_Nitro_Testnet.md
  docs/Useful_Addresses.md
Labels: cla-signed

#2371 Fix `--node.forwarder.rpc-mode='non-mutating'`
  packages/arb-rpc-node/cmd/arb-dev-node/arb-dev-node.go
  packages/arb-rpc-node/cmd/arb-node/arb-node.go
  packages/arb-rpc-node/web3/eth.go
  packages/arb-rpc-node/web3/ethclient.go
  packages/arb-rpc-node/web3/ethforwarder.go
  packages/arb-rpc-node/web3/launch.go
  packages/arb-util/configuration/configuration.go
Labels: cla-signed

#2362 feat: implement ERC165 on L1 token bridge
  packages/arb-bridge-peripherals/contracts/tokenbridge/ethereum/gateway/L1ArbitrumGateway.sol
  packages/arb-bridge-peripherals/contracts/tokenbridge/ethereum/gateway/L1GatewayRouter.sol
  packages/arb-bridge-peripherals/contracts/tokenbridge/libraries/ERC165.sol
  packages/arb-bridge-peripherals/contracts/tokenbridge/libraries/IERC165.sol
  packages/arb-bridge-peripherals/test/canonicalBridge.l1.ts
  packages/arb-bridge-peripherals/test/customGateway.e2e.ts
  packages/arb-bridge-peripherals/test/gatewayRouter.l1.ts
  packages/arb-bridge-peripherals/test/wethBridge.l1.ts
Labels: cla-signed

#2377 Update running nitro node docs to use beta.3
  docs/Running_Nitro_Node.md
Labels: cla-signed

#2378 Update documentation with correct default urls
  docs/Running_Nitro_Node.md
Labels: cla-signed

#2379 Remove unused parameter
  packages/arb-util/configuration/configuration.go
Labels: cla-signed

#2380 Change goerli nitro doc title from devnet to testnet
  docs/Running_Nitro_Node.md
Labels: cla-signed

#2381 Fix require-version parameter
  packages/arb-util/configuration/configuration.go
Labels: cla-signed

#2382 Handle unexpected feed values better
  packages/arb-util/broadcastclient/broadcastclient.go
Labels: cla-signed

#2376 refactor custom refund entrypoint to only be available in L1
  packages/arb-bridge-eth/contracts/interfaces/IERC721.sol
  packages/arb-bridge-peripherals/contracts/tokenbridge/arbitrum/gateway/L2ArbitrumGateway.sol
  packages/arb-bridge-peripherals/contracts/tokenbridge/ethereum/gateway/IL1ArbitrumGateway.sol
  packages/arb-bridge-peripherals/contracts/tokenbridge/ethereum/gateway/IL1GatewayRouter.sol
  packages/arb-bridge-peripherals/contracts/tokenbridge/ethereum/gateway/L1ArbitrumGateway.sol
  packages/arb-bridge-peripherals/contracts/tokenbridge/ethereum/gateway/L1GatewayRouter.sol
  packages/arb-bridge-peripherals/contracts/tokenbridge/libraries/gateway/GatewayRouter.sol
  packages/arb-bridge-peripherals/contracts/tokenbridge/libraries/gateway/ITokenGateway.sol
  packages/arb-bridge-peripherals/contracts/tokenbridge/test/InterfaceCompatibilityTester.sol
Labels: cla-signed

#2385 Bump undici to 5.8.0 to fix npm advisories
  package.json
  yarn.lock
Labels: cla-signed

#2374 unify pages to "public chains" page; add Nova info
  docs/AnyTrust.md
  docs/Developer_Quickstart.md
  docs/Mainnet.md
  docs/Public_Chains.md
  docs/Public_Nitro_Testnet.md
  docs/Public_Testnet.md
  docs/Useful_Addresses.md
Labels: cla-signed

#2390 Fix sidebar title
  docs/Running_Goerli_Nitro_Node.md
Labels: cla-signed

#2392 Have goerli use beta.4 until config initialization fixed on latest
  docs/Running_Goerli_Nitro_Node.md
Labels: cla-signed

#2393 Update docs to use nitro beta.6
  docs/Running_Goerli_Nitro_Node.md
  docs/Running_Rinkeby_Nitro_Node.md
Labels: cla-signed

#2388 Remove virtual keywords
  packages/arb-bridge-peripherals/contracts/tokenbridge/ethereum/gateway/L1CustomGateway.sol
  packages/arb-bridge-peripherals/contracts/tokenbridge/ethereum/gateway/L1ERC20Gateway.sol
  packages/arb-bridge-peripherals/contracts/tokenbridge/ethereum/gateway/L1GatewayRouter.sol
Labels: arb-bridge-peripherals, cla-signed

#2395 refactor outbox state changes from bridge to migrator
  packages/arb-bridge-eth/contracts/bridge/Bridge.sol
  packages/arb-bridge-eth/contracts/bridge/NitroMigrator.sol
  packages/arb-bridge-eth/contracts/bridge/Old_Outbox/OldOutbox.sol
  packages/arb-bridge-eth/contracts/bridge/Outbox.sol
  packages/arb-bridge-eth/contracts/bridge/interfaces/IBridge.sol
Labels: cla-signed

#2394 Instead of bridge proxying old outboxes, change the outbox bridge
  packages/arb-bridge-eth/contracts/bridge/Bridge.sol
  packages/arb-bridge-eth/contracts/bridge/Inbox.sol
  packages/arb-bridge-eth/contracts/bridge/NitroMigrator.sol
  packages/arb-bridge-eth/contracts/bridge/Old_Outbox/OldOutbox.sol
  packages/arb-bridge-eth/contracts/bridge/Outbox.sol
  packages/arb-bridge-eth/contracts/bridge/SequencerInbox.sol
  packages/arb-bridge-eth/contracts/bridge/interfaces/IBridge.sol
  packages/arb-bridge-eth/contracts/bridge/interfaces/IOutbox.sol
  packages/arb-bridge-eth/contracts/libraries/NitroReadyQuery.sol
  packages/arb-bridge-eth/contracts/rollup/facets/IRollupFacets.sol
  packages/arb-bridge-eth/contracts/rollup/facets/RollupAdmin.sol
  packages/arb-bridge-eth/contracts/rollup/facets/RollupUser.sol
  packages/arb-bridge-eth/contracts/test_only/BridgeMock.sol
  packages/arb-upgrades/ethBridgeTasks.ts
Labels: cla-signed

#2396 Sort address table in state export
  packages/arb-avm-cpp/cavm/dumpstate.cpp
Labels: cla-signed

#2269 Add functionality to prepare for nitro transition
  packages/arb-avm-cpp/cavm/carbcore.cpp
  packages/arb-avm-cpp/cavm/carbcore.h
  packages/arb-avm-cpp/cavm/cexecutioncursor.cpp
  packages/arb-avm-cpp/cavm/cexecutioncursor.h
  packages/arb-avm-cpp/cmachine/arbcore.go
  packages/arb-avm-cpp/cmachine/executioncursor.go
  packages/arb-node-core/staker/validator.go
  packages/arb-rpc-node/batcher/sequencerBatcher.go
  packages/arb-util/configuration/configuration.go
  packages/arb-util/core/lookup.go
  packages/arb-util/machine/machine.go
Labels: cla-signed

#2401 Override the TransactionIndex of exported receipts
  packages/arb-rpc-node/nitroexport/crossdb.go
Labels: cla-signed

#2403 Make migrator work behind proxy
  packages/arb-bridge-eth/contracts/bridge/NitroMigrator.sol
  packages/arb-bridge-eth/deploy/NitroMigratorProxy.ts
  packages/arb-bridge-eth/deploy/NitroMigratorProxyAdmin.ts
Labels: cla-signed

#2402 Improve error message on execution cursor error
  packages/arb-avm-cpp/cavm/carbcore.cpp
Labels: cla-signed

#2397 Fix some link to testnet arbiscan
  docs/Useful_Addresses.md
Labels: cla-signed

#2410 Update nitro docs to use beta.7
  docs/Running_Goerli_Nitro_Node.md
  docs/Running_Rinkeby_Nitro_Node.md
Labels: cla-signed

#2412 Update Rinkeby Post-Nitro Addresses
  docs/Useful_Addresses.md
Labels: cla-signed

#2391 include nova in mainnet beta page
  docs/Mainnet.md
Labels: cla-signed

#2415 Fix Rinkeby Nitro rollup address
  docs/Useful_Addresses.md
Labels: cla-signed

#2411 Default rinkeby to not connect to sequencer
  packages/arb-rpc-node/aggregator/aggregator.go
  packages/arb-rpc-node/cmd/arb-node/arb-node.go
  packages/arb-util/configuration/configuration.go
Labels: cla-signed

#2417 Improve documentation and update version
  docs/Running_Goerli_Nitro_Node.md
  docs/Running_Rinkeby_Nitro_Node.md
Labels: cla-signed

#2418 Fix rinkeby nitro sequencer inbox address
  docs/Useful_Addresses.md
Labels: cla-signed
